# -*- coding: utf-8 -*-
"""Navigation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/178y_K2SThzqRiR3Iqa_xsLk8xAysqErn
"""

import math
import numpy as np
def return_waypoints(x,y,radius):
  waypoints = np.zeros((6,2))
  waypoints[0] = [x + (radius/math.sqrt(3)), y + radius]
  waypoints[1] = [x + (radius/math.sqrt(3)), y - radius]
  waypoints[2] = [x - (radius/math.sqrt(3)), y + radius]
  waypoints[3] = [x - (radius/math.sqrt(3)), y - radius]
  waypoints[4] = [x - radius, y]
  waypoints[5] = [x + radius, y]
  x = list(waypoints[:,0])
  y = list(waypoints[:,1])
  return x,y